version: "3"

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=acai
      - MONGO_INITDB_ROOT_PASSWORD=travel
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo"]
      interval: 10s
      timeout: 10s
      retries: 5
